-- -- Selecting equipment with quantity
-- SELECT CHARACTER.CHARACTER_ID, EQUIPMENT.TYPE, CHARACTER_EQUIPMENT.QUANTITY
-- FROM EQUIPMENT, CHARACTER_EQUIPMENT, CHARACTER
-- WHERE CHARACTER.CHARACTER_ID = CHARACTER_EQUIPMENT.CHARACTER_ID AND
--       EQUIPMENT.EQUIPMENT_ID = CHARACTER_EQUIPMENT.EQUIPMENT_ID
--

-- -- Selecting dead/alive characters
-- SELECT CHARACTER.NAME FROM CHARACTER
-- WHERE EXISTS(SELECT CHARACTER_ID FROM DEATH WHERE DEATH.DEATH_ID = CHARACTER.DEATH_ID)

-- SELECT CHARACTER.NAME FROM CHARACTER
-- WHERE NOT EXISTS(SELECT CHARACTER_ID FROM DEATH WHERE DEATH.DEATH_ID = CHARACTER.DEATH_ID)

-- -- Selecting adventures in sessions played between two dates
-- SELECT ADVENTURE.OBJECTIVE FROM ADVENTURE WHERE
-- ADVENTURE.ADVENTURE_ID
--   IN (
--     SELECT ADVENTURE_SESSION.ADVENTURE_ID
--     FROM ADVENTURE_SESSION, SESSIONS
--     WHERE ADVENTURE_SESSION.SESSION_ID = ADVENTURE.ADVENTURE_ID AND
--           SESSIONS.SESSION_ID = ADVENTURE_SESSION.SESSION_ID AND
--           SESSIONS."date" BETWEEN TO_DATE('1.3.2019', 'dd.mm.yyyy') AND TO_DATE('1.4.2019', 'dd.mm.yyyy')
--   )
